package com.greatlearning.javafsd.labone.emailapp;

public class Employee {
	
	// Variables or property naming and initialization
	private String	firstName;
	private String	lastName;
	private String	department;		//use switch case to store selected department name 
	private String	emailAddress; 	// generated by application
	private	String	password;		// generated by application
	
	// Generate Constructors
	/**
	 * @param firstName
	 * @param lastName
	 * @param department
	 */
	public Employee(String firstName, String lastName, String department) {
		//super();
		this.firstName = firstName;
		this.lastName = lastName;
		this.department = department;
	}
	
	// getter setter methods
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}

	public String getEmailAddress() {
		return emailAddress;
	}
	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	
	
}
